version: "3"
services:
    redis5:
        image: "redis-5"
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        working_dir: '/data'
        volumes:
            - "./data:/data"
        ports:
          - 16379:6379
